language: java
jdk:
  - oraclejdk8

before_script:
  - echo 'checking out dependency'
  - git clone git@github.com/timols/java-gitlab-api.git
  - cd java-gitlab-api
  - mvn clean verify
  - stat target/java-gitlab-api-4.0.1-SNAPSHOT.jar
  - cp target/java-gitlab-api-4.0.1-SNAPSHOT.jar ../de.weingardt.mylyn.gitlab.core/lib/
  - cd ..

script: mvn clean compile package
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
